### Add user valid payload
POST http://localhost:5000/users HTTP/1.1
content-type: application/json

{
    "username": "tester",    
    "password": "12345678",
    "fullname": "The Tester"
}

### Add user with invalid payload
POST http://localhost:5000/users HTTP/1.1
content-type: application/json

{
    "username": true,    
    "password": "12345678",
    "fullname": 123
}

### Get User

GET http://localhost:5000/users/user-DqXeIrt1v54dlQmY

### Get User invalid id
GET http://localhost:5000/users/xxx
